feat: Change the Code field value of contract account to txHash
rigochain/rigo-go pull request #136
Opened 2023-10-19 02:57 UTC by EokgiLee

2023-10-19 09:41 UTC, kylekwon-rigochain commented on protos/account.proto
> +  string code = 5;
`string code` 를 `bytes _code` 로 변경해주세요.

해당 필드에 넣어야할 값은 `string` 이 아닌 `[]byte` 타입으로.

2023-10-20 04:08 UTC, EokgiLee commented
> `Code` 필드가 `string` 으로 바뀌어야할 이유가 있나요? TxHash 를 넣는 다 해도 이를 `[]byte` 형태로 저장하는 것이 더 좋겠습니다.

[]byte로 원복하고, query에서 string으로 변환하도록 수정했습니다.
확인 부탁드립니다.

2023-10-20 06:59 UTC, kylekwon-rigochain requested changes
Account 의 Code 필드 타입을 `bytes.HexBytes` 로 설정

2023-10-20 07:00 UTC, kylekwon-rigochain commented
스마트컨트랙트 account 조회시 Code 필드에 컨트랙트 바이트코드가 리턴되었으나, 
이 값이 TxHash (컨트랙트 생성 Tx) 값으로 변경되었음을 rigoscan 팀과 공유 요망.

2023-10-20 09:52 UTC, kylekwon-rigochain approved these changes

2023-10-20 09:52 UTC, merged